pipeline{
    agent any

    stages {
        stage('Get Source'){
            steps{
                git url: 'https://github.com/arturcorreiajr/python-tcp-jenkins.git',
                credentialsId: 'springdeploy-user',
                branch: 'main'
            }

        }
        stage('Docker Build'){
            steps{
                script {
                    dockerapp = docker.build("arturcorreiajunior/python-tcp:${env.BUILD_ID}", '-f ./Dockerfile .')
                }
            }
        }
        stage('Docker Push Image'){
            steps{
                script {
                        docker.withRegistry('http://registry.hub.docker.com', 'github-token-jenkins'){
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
        stage('Deploy docker'){
            steps{
                script {
                    echo "arturcorreiajunior/python-tcp:${env.BUILD_ID}"
                    sh "docker stop python-tcp || true && docker rm python-tcp || true"
                    sh "docker run --name python-tcp -d -p 8080:80 python-tcp:${env.BUILD_ID}"
                }
            }

        }
    }
}