pipeline{
    agent any

    stages {
        stage('Get Source'){
            steps{
                git url: 'https://github.com/arturcorreiajr/python-tcp-jenkins.git', branch: 'main'
            }

        }
        stage('Docker Build'){
            steps{
                script {
                    dockerapp = docker.build("arturcorreiajunior/python-tcp:${env.BUILD_ID}",
                        '-f ./Dockerfile .')
                }
            }
        }
        stage('Docker Push Image'){
            steps{
                script {
                        docker.withRegistry('http://registry.hub.docker.com', 'github-token-jenkins'){
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
    }

}